# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 594)
        MainWindow.setMinimumSize(QtCore.QSize(809, 594))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.nDim = QtWidgets.QSpinBox(self.centralwidget)
        self.nDim.setMinimum(1)
        self.nDim.setObjectName("nDim")
        self.gridLayout.addWidget(self.nDim, 0, 1, 1, 1)
        self.Mode_2 = QtWidgets.QComboBox(self.centralwidget)
        self.Mode_2.setObjectName("Mode_2")
        self.Mode_2.addItem("")
        self.Mode_2.addItem("")
        self.gridLayout.addWidget(self.Mode_2, 4, 1, 1, 1)
        self.resultsDirectory = QtWidgets.QLineEdit(self.centralwidget)
        self.resultsDirectory.setObjectName("resultsDirectory")
        self.gridLayout.addWidget(self.resultsDirectory, 6, 0, 1, 1)
        self.lObj = QtWidgets.QLabel(self.centralwidget)
        self.lObj.setObjectName("lObj")
        self.gridLayout.addWidget(self.lObj, 1, 0, 1, 1)
        self.nObj = QtWidgets.QSpinBox(self.centralwidget)
        self.nObj.setMinimum(1)
        self.nObj.setObjectName("nObj")
        self.gridLayout.addWidget(self.nObj, 1, 1, 1, 1)
        self.lQual = QtWidgets.QLabel(self.centralwidget)
        self.lQual.setObjectName("lQual")
        self.gridLayout.addWidget(self.lQual, 2, 0, 1, 1)
        self.lDim = QtWidgets.QLabel(self.centralwidget)
        self.lDim.setObjectName("lDim")
        self.gridLayout.addWidget(self.lDim, 0, 0, 1, 1)
        self.nBatch = QtWidgets.QSpinBox(self.centralwidget)
        self.nBatch.setMinimum(1)
        self.nBatch.setObjectName("nBatch")
        self.gridLayout.addWidget(self.nBatch, 3, 1, 1, 1)
        self.nQual = QtWidgets.QSpinBox(self.centralwidget)
        self.nQual.setObjectName("nQual")
        self.gridLayout.addWidget(self.nQual, 2, 1, 1, 1)
        self.lBatch = QtWidgets.QLabel(self.centralwidget)
        self.lBatch.setObjectName("lBatch")
        self.gridLayout.addWidget(self.lBatch, 3, 0, 1, 1)
        self.dataDir = QtWidgets.QPushButton(self.centralwidget)
        self.dataDir.setObjectName("dataDir")
        self.gridLayout.addWidget(self.dataDir, 5, 1, 1, 1)
        self.dataDirectory = QtWidgets.QLineEdit(self.centralwidget)
        self.dataDirectory.setObjectName("dataDirectory")
        self.gridLayout.addWidget(self.dataDirectory, 5, 0, 1, 1)
        self.lMode = QtWidgets.QLabel(self.centralwidget)
        self.lMode.setObjectName("lMode")
        self.gridLayout.addWidget(self.lMode, 4, 0, 1, 1)
        self.resDir = QtWidgets.QPushButton(self.centralwidget)
        self.resDir.setObjectName("resDir")
        self.gridLayout.addWidget(self.resDir, 6, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 2, 1)
        self.ledLayout = QtWidgets.QGridLayout()
        self.ledLayout.setObjectName("ledLayout")
        self.gridLayout_2.addLayout(self.ledLayout, 1, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 1, 2, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tResponse = QtWidgets.QTableWidget(self.centralwidget)
        self.tResponse.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tResponse.sizePolicy().hasHeightForWidth())
        self.tResponse.setSizePolicy(sizePolicy)
        self.tResponse.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tResponse.setRowCount(1)
        self.tResponse.setColumnCount(2)
        self.tResponse.setObjectName("tResponse")
        item = QtWidgets.QTableWidgetItem()
        self.tResponse.setVerticalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.tResponse)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.tConditions = QtWidgets.QTableWidget(self.centralwidget)
        self.tConditions.setEnabled(False)
        self.tConditions.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tConditions.setRowCount(1)
        self.tConditions.setColumnCount(2)
        self.tConditions.setObjectName("tConditions")
        self.tConditions.horizontalHeader().setVisible(True)
        self.tConditions.verticalHeader().setVisible(True)
        self.tConditions.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tConditions, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 0, 2, 1)
        self.figLayout = QtWidgets.QGridLayout()
        self.figLayout.setObjectName("figLayout")
        self.gridLayout_2.addLayout(self.figLayout, 2, 1, 3, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Mode_2.setItemText(0, _translate("MainWindow", "Online"))
        self.Mode_2.setItemText(1, _translate("MainWindow", "Offline"))
        self.lObj.setText(_translate("MainWindow", "Number of Objectives"))
        self.lQual.setText(_translate("MainWindow", "Number of Qualitative Variables"))
        self.lDim.setText(_translate("MainWindow", "Dimension"))
        self.lBatch.setText(_translate("MainWindow", "Batch Size"))
        self.dataDir.setText(_translate("MainWindow", "Data Folder"))
        self.lMode.setText(_translate("MainWindow", "Mode"))
        self.resDir.setText(_translate("MainWindow", "Results Folder"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lower"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Upper"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Watcher Active"))
        self.label_2.setText(_translate("MainWindow", "Conditions to Run"))
        self.label_3.setText(_translate("MainWindow", "Response"))
        item = self.tResponse.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Response"))
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.label_4.setText(_translate("MainWindow", "Submit Data"))

